# Generated by Django 3.0.2 on 2021-12-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.SlugField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField()),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
    ]
