# Generated by Django 3.0.2 on 2021-12-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_auto_20211214_1741'),
        ('perfil', '0003_auto_20211214_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='filmes_vistos',
        ),
        migrations.AddField(
            model_name='perfil',
            name='filmes_vistos',
            field=models.ManyToManyField(related_name='filmes_perfil', to='filme.Filme'),
        ),
    ]
