# Generated by Django 3.0.2 on 2021-12-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0005_auto_20211214_1741'),
        ('perfil', '0004_auto_20211214_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to='filme.Filme'),
        ),
    ]
