# Generated by Django 3.0.2 on 2021-12-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='total_filmes_vistos',
            field=models.IntegerField(default=0),
        ),
    ]
