# Generated by Django 3.0.2 on 2021-12-14 16:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filme', '0003_filme_nota_publico'),
        ('perfil', '0002_perfil_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resenha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrelas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('curtidas', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField()),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filme_resenha', to='filme.Filme')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil_resenha', to='perfil.Perfil')),
            ],
            options={
                'db_table': 'resenha',
            },
        ),
    ]
