# Generated by Django 3.0.2 on 2021-12-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
