# Generated by Django 3.0.2 on 2021-12-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resenha', '0002_resenha_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='texto',
            field=models.TextField(default=' '),
        ),
    ]
