# Generated by Django 3.0.2 on 2021-12-14 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('nome_original', models.CharField(max_length=100)),
                ('sinopse', models.TextField(default='Esse filme ainda não tem uma sinopse.')),
                ('ano', models.CharField(blank=True, default='0000', max_length=4)),
                ('duracao', models.DecimalField(blank=True, decimal_places=1, max_digits=5)),
                ('diretor', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=70)),
                ('imagem', models.CharField(max_length=100)),
                ('banner', models.CharField(blank=True, max_length=100)),
                ('data_cadastro', models.DateField()),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filmes', to='genero.Genero')),
            ],
            options={
                'db_table': 'filme',
            },
        ),
    ]
