# Generated by Django 3.0.2 on 2021-12-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
        ('filme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='genero',
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(to='genero.Genero'),
        ),
    ]
