# Generated by Django 3.0.2 on 2021-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0002_auto_20211214_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='nota_publico',
            field=models.IntegerField(default=0),
        ),
    ]
