# Generated by Django 3.0.2 on 2021-12-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filme', '0003_filme_nota_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nome_original',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='filme',
            name='nota_publico',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
