# Generated by Django 3.0.2 on 2021-12-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genero', '0001_initial'),
        ('filme', '0004_auto_20211214_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(related_name='generos', to='genero.Genero'),
        ),
    ]
