# Generated by Django 3.0.2 on 2021-12-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filme', '0003_filme_nota_publico'),
        ('perfil', '0002_perfil_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('curtidas', models.IntegerField(default=0)),
                ('data_cadastro', models.DateField()),
                ('filmes', models.ManyToManyField(related_name='filmes', to='filme.Filme')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perfil', to='perfil.Perfil')),
            ],
            options={
                'db_table': 'lista',
            },
        ),
    ]
